apiVersion: v1
kind: Pod
metadata:
  name: embed-app-pod
spec:
  containers:
  - name: embed-app-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: embed-app-public
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: embed-app-public
    configMap:
      name: embed-app-public